apiVersion: v1
kind: Service
metadata:
  name: agentland
  namespace: agentland
spec:
  selector:
    app: agentland
  ports:
  - name: proxy
    port: 4000
    targetPort: 4000
  - name: api
    port: 4001
    targetPort: 4001
